export const USERNAME_TEXT = 'USERNAME_TEXT';
export const PASSWORD_TEXT = 'PASSWORD_TEXT';
export const USERNAME_BACKSPACE = 'USERNAME_BACKSPACE';
export const PASSWORD_BACKSPACE = 'PASSWORD_BACKSPACE';

